--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 750.0000, height = 1334.0000})

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 255, g = 255, b = 255})
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(27)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setPosition(511.0000, 507.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPositionPercentX(0.6813)
layout:setPositionPercentY(0.3801)
layout:setPercentWidth(0.2667)
layout:setPercentHeight(0.1499)
layout:setSize({width = 200.0000, height = 200.0000})
layout:setLeftMargin(511.0000)
layout:setRightMargin(39.0000)
layout:setTopMargin(627.0000)
layout:setBottomMargin(507.0000)
Layer:addChild(Panel_1)

--Create btnTest
local btnTest = ccui.Button:create()
btnTest:ignoreContentAdaptWithSize(false)
btnTest:loadTextureNormal("Default/Button_Normal.png",0)
btnTest:loadTexturePressed("Default/Button_Press.png",0)
btnTest:loadTextureDisabled("Default/Button_Disable.png",0)
btnTest:setTitleFontSize(24)
btnTest:setTitleText("点我测试")
btnTest:setTitleColor({r = 65, g = 65, b = 70})
btnTest:setScale9Enabled(true)
btnTest:setCapInsets({x = 15, y = 11, width = 135, height = 64})
btnTest:setLayoutComponentEnabled(true)
btnTest:setName("btnTest")
btnTest:setTag(35)
btnTest:setCascadeColorEnabled(true)
btnTest:setCascadeOpacityEnabled(true)
btnTest:setPosition(375.0000, 667.0000)
if callBackProvider~=nil then
      btnTest:addClickEventListener(callBackProvider("layer_game.lua", btnTest, "onTestClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btnTest)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.2200)
layout:setPercentHeight(0.0645)
layout:setSize({width = 165.0000, height = 86.0000})
layout:setLeftMargin(292.5000)
layout:setRightMargin(292.5000)
layout:setTopMargin(624.0000)
layout:setBottomMargin(624.0000)
Layer:addChild(btnTest)

--Create btnClose
local btnClose = ccui.Button:create()
btnClose:ignoreContentAdaptWithSize(false)
btnClose:loadTextureNormal("Default/Button_Normal.png",0)
btnClose:loadTexturePressed("Default/Button_Press.png",0)
btnClose:loadTextureDisabled("Default/Button_Disable.png",0)
btnClose:setTitleFontSize(14)
btnClose:setTitleColor({r = 65, g = 65, b = 70})
btnClose:setScale9Enabled(true)
btnClose:setCapInsets({x = 30, y = 68, width = 82, height = 41})
btnClose:setLayoutComponentEnabled(true)
btnClose:setName("btnClose")
btnClose:setTag(36)
btnClose:setCascadeColorEnabled(true)
btnClose:setCascadeOpacityEnabled(true)
btnClose:setPosition(675.8055, 909.6289)
if callBackProvider~=nil then
      btnClose:addClickEventListener(callBackProvider("layer_game.lua", btnClose, "onCloseClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btnClose)
layout:setPositionPercentX(0.9011)
layout:setPositionPercentY(0.6819)
layout:setPercentWidth(0.1893)
layout:setPercentHeight(0.1042)
layout:setSize({width = 142.0000, height = 139.0000})
layout:setLeftMargin(604.8055)
layout:setRightMargin(3.1945)
layout:setTopMargin(354.8711)
layout:setBottomMargin(840.1289)
Layer:addChild(btnClose)

--Create FileNode_1
innerCSD = require("views.node_hud")
innerProject = innerCSD.create(callBackProvider)
local FileNode_1 = innerProject.root
FileNode_1.animation = innerProject.animation
FileNode_1:setName("FileNode_1")
FileNode_1:setTag(15)
FileNode_1:setCascadeColorEnabled(true)
FileNode_1:setCascadeOpacityEnabled(true)
FileNode_1:setPosition(-1.0000, 1133.1850)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_1)
layout:setPositionPercentX(-0.0013)
layout:setPositionPercentY(0.8495)
layout:setLeftMargin(-1.0000)
layout:setRightMargin(751.0000)
layout:setTopMargin(200.8152)
layout:setBottomMargin(1133.1850)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_1:runAction(innerProject.animation)
Layer:addChild(FileNode_1)

--Create TextField_3
local TextField_3 = ccui.TextField:create()
TextField_3:ignoreContentAdaptWithSize(false)
tolua.cast(TextField_3:getVirtualRenderer(), "cc.Label"):setLineBreakWithoutSpace(true)
TextField_3:setFontName("Resource/font/font.ttf")
TextField_3:setFontSize(36)
TextField_3:setPlaceHolder("123")
TextField_3:setString([[]])
TextField_3:setMaxLength(10)
TextField_3:setTouchEnabled(false);
TextField_3:setLayoutComponentEnabled(true)
TextField_3:setName("TextField_3")
TextField_3:setTag(56)
TextField_3:setCascadeColorEnabled(true)
TextField_3:setCascadeOpacityEnabled(true)
TextField_3:setPosition(737.0000, 631.0000)
TextField_3:setColor({r = 255, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(TextField_3)
layout:setPositionPercentX(0.9827)
layout:setPositionPercentY(0.4730)
layout:setPercentWidth(0.4560)
layout:setPercentHeight(0.0547)
layout:setSize({width = 342.0000, height = 73.0000})
layout:setLeftMargin(566.0000)
layout:setRightMargin(-158.0000)
layout:setTopMargin(666.5000)
layout:setBottomMargin(594.5000)
Layer:addChild(TextField_3)

--Create ListView_1
local ListView_1 = ccui.ListView:create()
ListView_1:setItemsMargin(15)
ListView_1:setDirection(1)
ListView_1:setGravity(0)
ListView_1:ignoreContentAdaptWithSize(false)
ListView_1:setBackGroundImage("",0)
ListView_1:setClippingEnabled(true)
ListView_1:setBackGroundColorType(1)
ListView_1:setBackGroundColor({r = 150, g = 150, b = 255})
ListView_1:setBackGroundColorOpacity(170)
ListView_1:setLayoutComponentEnabled(true)
ListView_1:setName("ListView_1")
ListView_1:setTag(69)
ListView_1:setCascadeColorEnabled(true)
ListView_1:setCascadeOpacityEnabled(true)
ListView_1:setPosition(84.0000, 698.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ListView_1)
layout:setPositionPercentX(0.1120)
layout:setPositionPercentY(0.5232)
layout:setPercentWidth(0.2667)
layout:setPercentHeight(0.1499)
layout:setSize({width = 200.0000, height = 200.0000})
layout:setLeftMargin(84.0000)
layout:setRightMargin(466.0000)
layout:setTopMargin(436.0000)
layout:setBottomMargin(698.0000)
Layer:addChild(ListView_1)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("Default/ImageFile.png",0)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(70)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(23.0000, 267.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentX(0.1150)
layout:setPositionPercentY(0.9207)
layout:setPercentWidth(0.2300)
layout:setPercentHeight(0.1586)
layout:setSize({width = 46.0000, height = 46.0000})
layout:setRightMargin(154.0000)
layout:setBottomMargin(244.0000)
ListView_1:pushBackCustomItem(Image_1)

--Create Image_2
local Image_2 = ccui.ImageView:create()
Image_2:ignoreContentAdaptWithSize(false)
Image_2:loadTexture("Default/ImageFile.png",0)
Image_2:setLayoutComponentEnabled(true)
Image_2:setName("Image_2")
Image_2:setLocalZOrder(1)
Image_2:setTag(71)
Image_2:setCascadeColorEnabled(true)
Image_2:setCascadeOpacityEnabled(true)
Image_2:setPosition(23.0000, 206.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_2)
layout:setPositionPercentX(0.1150)
layout:setPositionPercentY(0.7103)
layout:setPercentWidth(0.2300)
layout:setPercentHeight(0.1586)
layout:setSize({width = 46.0000, height = 46.0000})
layout:setRightMargin(154.0000)
layout:setTopMargin(61.0000)
layout:setBottomMargin(183.0000)
ListView_1:pushBackCustomItem(Image_2)

--Create Image_3
local Image_3 = ccui.ImageView:create()
Image_3:ignoreContentAdaptWithSize(false)
Image_3:loadTexture("Default/ImageFile.png",0)
Image_3:setLayoutComponentEnabled(true)
Image_3:setName("Image_3")
Image_3:setLocalZOrder(2)
Image_3:setTag(72)
Image_3:setCascadeColorEnabled(true)
Image_3:setCascadeOpacityEnabled(true)
Image_3:setPosition(23.0000, 145.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_3)
layout:setPositionPercentX(0.1150)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.2300)
layout:setPercentHeight(0.1586)
layout:setSize({width = 46.0000, height = 46.0000})
layout:setRightMargin(154.0000)
layout:setTopMargin(122.0000)
layout:setBottomMargin(122.0000)
ListView_1:pushBackCustomItem(Image_3)

--Create Image_4
local Image_4 = ccui.ImageView:create()
Image_4:ignoreContentAdaptWithSize(false)
Image_4:loadTexture("Default/ImageFile.png",0)
Image_4:setLayoutComponentEnabled(true)
Image_4:setName("Image_4")
Image_4:setLocalZOrder(3)
Image_4:setTag(73)
Image_4:setCascadeColorEnabled(true)
Image_4:setCascadeOpacityEnabled(true)
Image_4:setPosition(23.0000, 84.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_4)
layout:setPositionPercentX(0.1150)
layout:setPositionPercentY(0.2897)
layout:setPercentWidth(0.2300)
layout:setPercentHeight(0.1586)
layout:setSize({width = 46.0000, height = 46.0000})
layout:setRightMargin(154.0000)
layout:setTopMargin(183.0000)
layout:setBottomMargin(61.0000)
ListView_1:pushBackCustomItem(Image_4)

--Create Image_5
local Image_5 = ccui.ImageView:create()
Image_5:ignoreContentAdaptWithSize(false)
Image_5:loadTexture("Default/ImageFile.png",0)
Image_5:setLayoutComponentEnabled(true)
Image_5:setName("Image_5")
Image_5:setLocalZOrder(4)
Image_5:setTag(74)
Image_5:setCascadeColorEnabled(true)
Image_5:setCascadeOpacityEnabled(true)
Image_5:setPosition(23.0000, 23.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_5)
layout:setPositionPercentX(0.1150)
layout:setPositionPercentY(0.0793)
layout:setPercentWidth(0.2300)
layout:setPercentHeight(0.1586)
layout:setSize({width = 46.0000, height = 46.0000})
layout:setRightMargin(154.0000)
layout:setTopMargin(244.0000)
ListView_1:pushBackCustomItem(Image_5)

--Create ArmatureNode_1
local ArmatureNode_1 = ccs.Armature:create()
ArmatureNode_1:setName("ArmatureNode_1")
ArmatureNode_1:setTag(75)
ArmatureNode_1:setCascadeColorEnabled(true)
ArmatureNode_1:setCascadeOpacityEnabled(true)
ArmatureNode_1:setPosition(446.0000, 991.3948)
layout = ccui.LayoutComponent:bindLayoutComponent(ArmatureNode_1)
layout:setPositionPercentX(0.5947)
layout:setPositionPercentY(0.7432)
layout:setLeftMargin(446.0000)
layout:setRightMargin(304.0000)
layout:setTopMargin(342.6052)
layout:setBottomMargin(991.3948)
ccs.ArmatureDataManager:getInstance():addArmatureFileInfo("Default/DemoPlayer.ExportJson")
ArmatureNode_1:init("DemoPlayer")
ArmatureNode_1:getAnimation():play("walk",-1, 1)
Layer:addChild(ArmatureNode_1)

--Create Map_1
local Map_1 = cc.TMXTiledMap:create("Default/defaultMap.tmx")
Map_1:setName("Map_1")
Map_1:setTag(76)
Map_1:setCascadeColorEnabled(true)
Map_1:setCascadeOpacityEnabled(true)
Map_1:setPosition(413.0000, 855.1158)
layout = ccui.LayoutComponent:bindLayoutComponent(Map_1)
layout:setPositionPercentX(0.5507)
layout:setPositionPercentY(0.6410)
layout:setPercentWidth(0.1707)
layout:setPercentHeight(0.0480)
layout:setSize({width = 128.0000, height = 64.0000})
layout:setLeftMargin(413.0000)
layout:setRightMargin(209.0000)
layout:setTopMargin(414.8842)
layout:setBottomMargin(855.1158)
Layer:addChild(Map_1)

--Create BitmapFontLabel_1
local BitmapFontLabel_1 = ccui.TextBMFont:create()
BitmapFontLabel_1:setFntFile("Resource/font/font-dynasty.fnt")
BitmapFontLabel_1:setString([[123456]])
BitmapFontLabel_1:setLayoutComponentEnabled(true)
BitmapFontLabel_1:setName("BitmapFontLabel_1")
BitmapFontLabel_1:setTag(26)
BitmapFontLabel_1:setCascadeColorEnabled(true)
BitmapFontLabel_1:setCascadeOpacityEnabled(true)
BitmapFontLabel_1:setPosition(260.0000, 537.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(BitmapFontLabel_1)
layout:setPositionPercentX(0.3467)
layout:setPositionPercentY(0.4025)
layout:setPercentWidth(0.3107)
layout:setPercentHeight(0.0615)
layout:setSize({width = 233.0000, height = 82.0000})
layout:setLeftMargin(143.5000)
layout:setRightMargin(373.5000)
layout:setTopMargin(756.0000)
layout:setBottomMargin(496.0000)
Layer:addChild(BitmapFontLabel_1)

--Create AtlasLabel_1
local AtlasLabel_1 = ccui.TextAtlas:create([[./0123456789]],
													"Default/TextAtlas.png",
													14,
													18,
													".")
AtlasLabel_1:setLayoutComponentEnabled(true)
AtlasLabel_1:setName("AtlasLabel_1")
AtlasLabel_1:setTag(28)
AtlasLabel_1:setCascadeColorEnabled(true)
AtlasLabel_1:setCascadeOpacityEnabled(true)
AtlasLabel_1:setPosition(506.0000, 587.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(AtlasLabel_1)
layout:setPositionPercentX(0.6747)
layout:setPositionPercentY(0.4400)
layout:setPercentWidth(0.2240)
layout:setPercentHeight(0.0135)
layout:setSize({width = 168.0000, height = 18.0000})
layout:setLeftMargin(422.0000)
layout:setRightMargin(160.0000)
layout:setTopMargin(738.0000)
layout:setBottomMargin(578.0000)
Layer:addChild(AtlasLabel_1)

--Create Particle_1
local Particle_1 = cc.ParticleSystemQuad:create("Resource/testpar.plist")
Particle_1:setName("Particle_1")
Particle_1:setTag(30)
Particle_1:setCascadeColorEnabled(true)
Particle_1:setCascadeOpacityEnabled(true)
Particle_1:setPosition(124.0000, 543.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Particle_1)
layout:setPositionPercentX(0.1653)
layout:setPositionPercentY(0.4070)
layout:setLeftMargin(124.0000)
layout:setRightMargin(626.0000)
layout:setTopMargin(791.0000)
layout:setBottomMargin(543.0000)
Particle_1:setBlendFunc({src = 770, dst = 1})
Layer:addChild(Particle_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

