--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_1:setBackGroundColorOpacity(0)
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(38)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setAnchorPoint(0.5000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setSize({width = 640.0000, height = 200.0000})
layout:setLeftMargin(-320.0000)
layout:setRightMargin(-320.0000)
layout:setTopMargin(-200.0000)
Node:addChild(Panel_1)

--Create bottom_1
local bottom_1 = cc.Sprite:create("Resource/atlas/bottom.png")
bottom_1:setName("bottom_1")
bottom_1:setTag(39)
bottom_1:setCascadeColorEnabled(true)
bottom_1:setCascadeOpacityEnabled(true)
bottom_1:setVisible(false)
bottom_1:setPosition(325.0321, -100.0000)
bottom_1:setScaleX(0.8000)
bottom_1:setScaleY(0.8000)
bottom_1:setOpacity(86)
layout = ccui.LayoutComponent:bindLayoutComponent(bottom_1)
layout:setPositionPercentX(0.5079)
layout:setPositionPercentY(-0.5000)
layout:setPercentWidth(1.1250)
layout:setPercentHeight(1.0850)
layout:setSize({width = 720.0000, height = 217.0000})
layout:setLeftMargin(-34.9679)
layout:setRightMargin(-45.0321)
layout:setTopMargin(191.5000)
layout:setBottomMargin(-208.5000)
bottom_1:setBlendFunc({src = 1, dst = 771})
Panel_1:addChild(bottom_1)

--Create Button_1
local Button_1 = ccui.Button:create()
Button_1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/common.plist")
Button_1:loadTextureNormal("btn-165-86-3.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/common.plist")
Button_1:loadTexturePressed("btn-165-86-2.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/common.plist")
Button_1:loadTextureDisabled("btn-165-86-1.png",1)
Button_1:setTitleFontName("Resource/font/FZY4K.ttf")
Button_1:setTitleFontSize(24)
Button_1:setTitleText("点我开始")
Button_1:setTitleColor({r = 0, g = 128, b = 0})
Button_1:setScale9Enabled(true)
Button_1:setCapInsets({x = 15, y = 11, width = 135, height = 64})
Button_1:setLayoutComponentEnabled(true)
Button_1:setName("Button_1")
Button_1:setTag(25)
Button_1:setCascadeColorEnabled(true)
Button_1:setCascadeOpacityEnabled(true)
Button_1:setPosition(356.8252, 280.8831)
if callBackProvider~=nil then
      Button_1:addClickEventListener(callBackProvider("node_bottom.lua", Button_1, "onStarClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(Button_1)
layout:setPositionPercentX(0.4956)
layout:setPositionPercentY(1.2944)
layout:setPercentWidth(0.2292)
layout:setPercentHeight(0.3963)
layout:setSize({width = 165.0000, height = 86.0000})
layout:setLeftMargin(274.3252)
layout:setRightMargin(280.6748)
layout:setTopMargin(-106.8831)
layout:setBottomMargin(237.8831)
bottom_1:addChild(Button_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(30)
result['animation']:setTimeSpeed(1.0000)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(5)
localFrame:setX(325.0321)
localFrame:setY(-100.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(6)
localFrame:setX(325.0321)
localFrame:setY(60.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(bottom_1)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(4)
localFrame:setScaleX(0.8000)
localFrame:setScaleY(0.8000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(5)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.8333)
localFrame:setScaleY(0.8333)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(7)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(bottom_1)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(bottom_1)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(86)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(bottom_1)

--Create VisibleForFrameTimeline
local VisibleForFrameTimeline = ccs.Timeline:create()

localFrame = ccs.VisibleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(false)
localFrame:setVisible(false)
VisibleForFrameTimeline:addFrame(localFrame)

localFrame = ccs.VisibleFrame:create()
localFrame:setFrameIndex(5)
localFrame:setTween(false)
localFrame:setVisible(true)
VisibleForFrameTimeline:addFrame(localFrame)

result['animation']:addTimeline(VisibleForFrameTimeline)
VisibleForFrameTimeline:setNode(bottom_1)

--Create FrameEventTimeline
local FrameEventTimeline = ccs.Timeline:create()

localFrame = ccs.EventFrame:create()
localFrame:setFrameIndex(5)
localFrame:setTween(false)
localFrame:setEvent("start1")
FrameEventTimeline:addFrame(localFrame)

localFrame = ccs.EventFrame:create()
localFrame:setFrameIndex(29)
localFrame:setTween(false)
localFrame:setEvent("")
FrameEventTimeline:addFrame(localFrame)

localFrame = ccs.EventFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(false)
localFrame:setEvent("startend")
FrameEventTimeline:addFrame(localFrame)

result['animation']:addTimeline(FrameEventTimeline)
FrameEventTimeline:setNode(bottom_1)
--Create Animation List
local enter = {name="enter", startIndex=0, endIndex=30}
result['animation']:addAnimationInfo(enter)

result['root'] = Node
return result;
end

return Result

