--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 640.0000, height = 960.0000})

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(7)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setPosition(-5.0419, 0.9916)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPositionPercentX(-0.0079)
layout:setPositionPercentY(0.0010)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 640.0000, height = 960.0000})
layout:setLeftMargin(-5.0419)
layout:setRightMargin(5.0419)
layout:setTopMargin(-0.9916)
layout:setBottomMargin(0.9916)
Layer:addChild(Panel_1)

--Create Button_1
local Button_1 = ccui.Button:create()
Button_1:ignoreContentAdaptWithSize(false)
Button_1:loadTextureNormal("Resource/atlas/btn-start.png",0)
Button_1:loadTexturePressed("Resource/atlas/btn-start-2.png",0)
Button_1:loadTextureDisabled("Default/Button_Disable.png",0)
Button_1:setTitleFontSize(14)
Button_1:setTitleColor({r = 65, g = 65, b = 70})
Button_1:setScale9Enabled(true)
Button_1:setCapInsets({x = 15, y = 11, width = 279, height = 80})
Button_1:setLayoutComponentEnabled(true)
Button_1:setName("Button_1")
Button_1:setTag(9)
Button_1:setCascadeColorEnabled(true)
Button_1:setCascadeOpacityEnabled(true)
Button_1:setPosition(325.0417, 347.8515)
if callBackProvider~=nil then
      Button_1:addClickEventListener(callBackProvider("layer_plane_main.lua", Button_1, "onStartClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(Button_1)
layout:setPositionPercentX(0.5079)
layout:setPositionPercentY(0.3623)
layout:setPercentWidth(0.4828)
layout:setPercentHeight(0.1063)
layout:setSize({width = 309.0000, height = 102.0000})
layout:setLeftMargin(170.5417)
layout:setRightMargin(160.4583)
layout:setTopMargin(561.1485)
layout:setBottomMargin(296.8515)
Panel_1:addChild(Button_1)

--Create title_1
local title_1 = cc.Sprite:create("Resource/atlas/title.png")
title_1:setName("title_1")
title_1:setTag(6)
title_1:setCascadeColorEnabled(true)
title_1:setCascadeOpacityEnabled(true)
title_1:setPosition(323.8009, 656.7756)
layout = ccui.LayoutComponent:bindLayoutComponent(title_1)
layout:setPositionPercentX(0.5059)
layout:setPositionPercentY(0.6841)
layout:setPercentWidth(0.8844)
layout:setPercentHeight(0.2281)
layout:setSize({width = 566.0000, height = 219.0000})
layout:setLeftMargin(40.8009)
layout:setRightMargin(33.1991)
layout:setTopMargin(193.7244)
layout:setBottomMargin(547.2756)
title_1:setBlendFunc({src = 1, dst = 771})
Layer:addChild(title_1)

--Create Sprite_2
local Sprite_2 = cc.Sprite:create("Resource/atlas/plane-2.png")
Sprite_2:setName("Sprite_2")
Sprite_2:setTag(8)
Sprite_2:setCascadeColorEnabled(true)
Sprite_2:setCascadeOpacityEnabled(true)
Sprite_2:setPosition(-92.4811, 544.6230)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_2)
layout:setPositionPercentX(-0.1445)
layout:setPositionPercentY(0.5673)
layout:setPercentWidth(0.2609)
layout:setPercentHeight(0.0875)
layout:setSize({width = 167.0000, height = 84.0000})
layout:setLeftMargin(-175.9811)
layout:setRightMargin(648.9811)
layout:setTopMargin(373.3770)
layout:setBottomMargin(502.6230)
Sprite_2:setBlendFunc({src = 1, dst = 771})
Layer:addChild(Sprite_2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(90)
result['animation']:setTimeSpeed(1.0000)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setX(-92.4811)
localFrame:setY(544.6230)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-92.4000)
localFrame:setY(544.6230)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(90)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(780.0000)
localFrame:setY(544.6230)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(Sprite_2)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(90)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(Sprite_2)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(90)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(Sprite_2)
--Create Animation List
local play = {name="play", startIndex=0, endIndex=90}
result['animation']:addAnimationInfo(play)

result['root'] = Layer
return result;
end

return Result

