--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create sd1
local sd1 = ccui.Slider:create()
sd1:ignoreContentAdaptWithSize(false)
sd1:loadBarTexture("Default/Slider_Back.png",0)
sd1:loadProgressBarTexture("Default/Slider_PressBar.png",0)
sd1:loadSlidBallTextureNormal("Default/SliderNode_Normal.png",0)
sd1:loadSlidBallTexturePressed("Default/SliderNode_Press.png",0)
sd1:loadSlidBallTextureDisabled("Default/SliderNode_Disable.png",0)
sd1:setPercent(50)
sd1:setLayoutComponentEnabled(true)
sd1:setName("sd1")
sd1:setTag(8)
sd1:setCascadeColorEnabled(true)
sd1:setCascadeOpacityEnabled(true)
sd1:setPosition(494.2631, 1807.9390)
if callBackProvider~=nil then
      sd1:addEventListener(callBackProvider("color_adjust.lua", sd1, "changeValue"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(sd1)
layout:setPositionPercentX(0.4577)
layout:setPositionPercentY(0.9416)
layout:setPercentWidth(0.4508)
layout:setPercentHeight(0.0202)
layout:setSize({width = 486.8813, height = 38.7307})
layout:setLeftMargin(250.8224)
layout:setRightMargin(342.2963)
layout:setTopMargin(92.6957)
layout:setBottomMargin(1788.5740)
Layer:addChild(sd1)

--Create t1
local t1 = ccui.Text:create()
t1:ignoreContentAdaptWithSize(true)
t1:setTextAreaSize({width = 0, height = 0})
t1:setFontSize(72)
t1:setString([[1]])
t1:setLayoutComponentEnabled(true)
t1:setName("t1")
t1:setTag(11)
t1:setCascadeColorEnabled(true)
t1:setCascadeOpacityEnabled(true)
t1:setPosition(877.4308, 1804.9360)
layout = ccui.LayoutComponent:bindLayoutComponent(t1)
layout:setPositionPercentX(0.8124)
layout:setPositionPercentY(0.9401)
layout:setPercentWidth(0.0380)
layout:setPercentHeight(0.0422)
layout:setSize({width = 41.0000, height = 81.0000})
layout:setLeftMargin(856.9308)
layout:setRightMargin(182.0692)
layout:setTopMargin(74.5640)
layout:setBottomMargin(1764.4360)
Layer:addChild(t1)

--Create t2
local t2 = ccui.Text:create()
t2:ignoreContentAdaptWithSize(true)
t2:setTextAreaSize({width = 0, height = 0})
t2:setFontSize(72)
t2:setString([[1]])
t2:setLayoutComponentEnabled(true)
t2:setName("t2")
t2:setTag(12)
t2:setCascadeColorEnabled(true)
t2:setCascadeOpacityEnabled(true)
t2:setPosition(884.8494, 1704.3640)
layout = ccui.LayoutComponent:bindLayoutComponent(t2)
layout:setPositionPercentX(0.8193)
layout:setPositionPercentY(0.8877)
layout:setPercentWidth(0.0380)
layout:setPercentHeight(0.0422)
layout:setSize({width = 41.0000, height = 81.0000})
layout:setLeftMargin(864.3494)
layout:setRightMargin(174.6506)
layout:setTopMargin(175.1357)
layout:setBottomMargin(1663.8640)
Layer:addChild(t2)

--Create t3
local t3 = ccui.Text:create()
t3:ignoreContentAdaptWithSize(true)
t3:setTextAreaSize({width = 0, height = 0})
t3:setFontSize(72)
t3:setString([[1]])
t3:setLayoutComponentEnabled(true)
t3:setName("t3")
t3:setTag(13)
t3:setCascadeColorEnabled(true)
t3:setCascadeOpacityEnabled(true)
t3:setPosition(880.4283, 1593.4820)
layout = ccui.LayoutComponent:bindLayoutComponent(t3)
layout:setPositionPercentX(0.8152)
layout:setPositionPercentY(0.8299)
layout:setPercentWidth(0.0380)
layout:setPercentHeight(0.0422)
layout:setSize({width = 41.0000, height = 81.0000})
layout:setLeftMargin(859.9283)
layout:setRightMargin(179.0717)
layout:setTopMargin(286.0176)
layout:setBottomMargin(1552.9820)
Layer:addChild(t3)

--Create sd2
local sd2 = ccui.Slider:create()
sd2:ignoreContentAdaptWithSize(false)
sd2:loadBarTexture("Default/Slider_Back.png",0)
sd2:loadProgressBarTexture("Default/Slider_PressBar.png",0)
sd2:loadSlidBallTextureNormal("Default/SliderNode_Normal.png",0)
sd2:loadSlidBallTexturePressed("Default/SliderNode_Press.png",0)
sd2:loadSlidBallTextureDisabled("Default/SliderNode_Disable.png",0)
sd2:setPercent(50)
sd2:setLayoutComponentEnabled(true)
sd2:setName("sd2")
sd2:setTag(14)
sd2:setCascadeColorEnabled(true)
sd2:setCascadeOpacityEnabled(true)
sd2:setPosition(504.2653, 1706.4350)
if callBackProvider~=nil then
      sd2:addEventListener(callBackProvider("color_adjust.lua", sd2, "changeValue"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(sd2)
layout:setPositionPercentX(0.4669)
layout:setPositionPercentY(0.8888)
layout:setPercentWidth(0.4508)
layout:setPercentHeight(0.0202)
layout:setSize({width = 486.8813, height = 38.7307})
layout:setLeftMargin(260.8246)
layout:setRightMargin(332.2941)
layout:setTopMargin(194.1998)
layout:setBottomMargin(1687.0690)
Layer:addChild(sd2)

--Create sd3
local sd3 = ccui.Slider:create()
sd3:ignoreContentAdaptWithSize(false)
sd3:loadBarTexture("Default/Slider_Back.png",0)
sd3:loadProgressBarTexture("Default/Slider_PressBar.png",0)
sd3:loadSlidBallTextureNormal("Default/SliderNode_Normal.png",0)
sd3:loadSlidBallTexturePressed("Default/SliderNode_Press.png",0)
sd3:loadSlidBallTextureDisabled("Default/SliderNode_Disable.png",0)
sd3:setPercent(50)
sd3:setLayoutComponentEnabled(true)
sd3:setName("sd3")
sd3:setTag(15)
sd3:setCascadeColorEnabled(true)
sd3:setCascadeOpacityEnabled(true)
sd3:setPosition(511.6857, 1597.6190)
if callBackProvider~=nil then
      sd3:addEventListener(callBackProvider("color_adjust.lua", sd3, "changeValue"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(sd3)
layout:setPositionPercentX(0.4738)
layout:setPositionPercentY(0.8321)
layout:setPercentWidth(0.4508)
layout:setPercentHeight(0.0202)
layout:setSize({width = 486.8813, height = 38.7307})
layout:setLeftMargin(268.2450)
layout:setRightMargin(324.8737)
layout:setTopMargin(303.0160)
layout:setBottomMargin(1578.2530)
Layer:addChild(sd3)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

