--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 640.0000, height = 960.0000})

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_1:setBackGroundColorOpacity(102)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(63)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setAnchorPoint(0.5000, 0.5000)
Panel_1:setPosition(320.0000, 480.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.1719)
layout:setPercentHeight(1.3896)
layout:setSize({width = 750.0000, height = 1334.0000})
layout:setLeftMargin(-55.0000)
layout:setRightMargin(-55.0000)
layout:setTopMargin(-187.0000)
layout:setBottomMargin(-187.0000)
Layer:addChild(Panel_1)

--Create background_1
local background_1 = cc.Sprite:create("Resource/atlas/background.png")
background_1:setName("background_1")
background_1:setTag(62)
background_1:setCascadeColorEnabled(true)
background_1:setCascadeOpacityEnabled(true)
background_1:setPosition(375.0000, 667.0000)
background_1:setScaleX(0.6000)
background_1:setScaleY(0.6000)
layout = ccui.LayoutComponent:bindLayoutComponent(background_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9600)
layout:setPercentHeight(0.8531)
layout:setSize({width = 720.0000, height = 1138.0000})
layout:setLeftMargin(15.0000)
layout:setRightMargin(15.0000)
layout:setTopMargin(98.0000)
layout:setBottomMargin(98.0000)
background_1:setBlendFunc({src = 770, dst = 771})
Panel_1:addChild(background_1)

--Create Button_1
local Button_1 = ccui.Button:create()
Button_1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/common.plist")
Button_1:loadTextureNormal("btn-close.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/common.plist")
Button_1:loadTexturePressed("btn-close.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/common.plist")
Button_1:loadTextureDisabled("btn-close.png",1)
Button_1:setTitleFontSize(14)
Button_1:setTitleColor({r = 65, g = 65, b = 70})
Button_1:setScale9Enabled(true)
Button_1:setCapInsets({x = 15, y = 11, width = 112, height = 117})
Button_1:setLayoutComponentEnabled(true)
Button_1:setName("Button_1")
Button_1:setTag(64)
Button_1:setCascadeColorEnabled(true)
Button_1:setCascadeOpacityEnabled(true)
Button_1:setPosition(693.0334, 1121.8480)
if callBackProvider~=nil then
      Button_1:addClickEventListener(callBackProvider("layer_dialog.lua", Button_1, "onCloseClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(Button_1)
layout:setPositionPercentX(0.9625)
layout:setPositionPercentY(0.9858)
layout:setPercentWidth(0.1972)
layout:setPercentHeight(0.1221)
layout:setSize({width = 142.0000, height = 139.0000})
layout:setLeftMargin(622.0334)
layout:setRightMargin(-44.0335)
layout:setTopMargin(-53.3479)
layout:setBottomMargin(1052.3480)
background_1:addChild(Button_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(50)
result['animation']:setTimeSpeed(1.0000)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(375.0000)
localFrame:setY(667.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(20)
localFrame:setTween(true)
localFrame:setTweenType(4)
localFrame:setX(375.0000)
localFrame:setY(667.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(background_1)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(23)
localFrame:setScaleX(0.1000)
localFrame:setScaleY(0.1000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(20)
localFrame:setTween(true)
localFrame:setTweenType(4)
localFrame:setScaleX(0.6000)
localFrame:setScaleY(0.6000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(29)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.6000)
localFrame:setScaleY(0.6000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.6000)
localFrame:setScaleY(0.6000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(37)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.6000)
localFrame:setScaleY(0.6000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(50)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.0100)
localFrame:setScaleY(0.0100)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(background_1)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(23)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(20)
localFrame:setTween(true)
localFrame:setTweenType(10)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(background_1)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(50)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(background_1)

--Create FrameEventTimeline
local FrameEventTimeline = ccs.Timeline:create()

localFrame = ccs.EventFrame:create()
localFrame:setFrameIndex(50)
localFrame:setTween(false)
localFrame:setEvent("exitEnd")
FrameEventTimeline:addFrame(localFrame)

result['animation']:addTimeline(FrameEventTimeline)
FrameEventTimeline:setNode(background_1)
--Create Animation List
local enter = {name="enter", startIndex=0, endIndex=30}
result['animation']:addAnimationInfo(enter)
local exit = {name="exit", startIndex=30, endIndex=60}
result['animation']:addAnimationInfo(exit)

result['root'] = Layer
return result;
end

return Result

