--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 640.0000, height = 960.0000})

--Create background_1
local background_1 = cc.Sprite:create("Resource/atlas/background.png")
background_1:setName("background_1")
background_1:setTag(33)
background_1:setCascadeColorEnabled(true)
background_1:setCascadeOpacityEnabled(true)
background_1:setPosition(320.0000, 480.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(background_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.1250)
layout:setPercentHeight(1.1854)
layout:setSize({width = 720.0000, height = 1138.0000})
layout:setLeftMargin(-40.0000)
layout:setRightMargin(-40.0000)
layout:setTopMargin(-89.0000)
layout:setBottomMargin(-89.0000)
background_1:setBlendFunc({src = 770, dst = 771})
Layer:addChild(background_1)

--Create Button_1
local Button_1 = ccui.Button:create()
Button_1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/common.plist")
Button_1:loadTextureNormal("btn-165-86-3.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/common.plist")
Button_1:loadTexturePressed("btn-165-86-4.png",1)
Button_1:loadTextureDisabled("Default/Button_Disable.png",0)
Button_1:setTitleFontSize(14)
Button_1:setTitleText("Button")
Button_1:setTitleColor({r = 65, g = 65, b = 70})
Button_1:setScale9Enabled(true)
Button_1:setCapInsets({x = 15, y = 11, width = 135, height = 64})
Button_1:setLayoutComponentEnabled(true)
Button_1:setName("Button_1")
Button_1:setTag(6)
Button_1:setCascadeColorEnabled(true)
Button_1:setCascadeOpacityEnabled(true)
Button_1:setPosition(377.0000, 515.0000)
if callBackProvider~=nil then
      Button_1:addClickEventListener(callBackProvider("layer_back.lua", Button_1, "onButton"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(Button_1)
layout:setPositionPercentX(0.5891)
layout:setPositionPercentY(0.5365)
layout:setPercentWidth(0.2578)
layout:setPercentHeight(0.0896)
layout:setSize({width = 165.0000, height = 86.0000})
layout:setLeftMargin(294.5000)
layout:setRightMargin(180.5000)
layout:setTopMargin(402.0000)
layout:setBottomMargin(472.0000)
Layer:addChild(Button_1)

--Create Sprite_2
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/common.plist")
local Sprite_2 = cc.Sprite:createWithSpriteFrameName("btn-165-86-1.png")
Sprite_2:setName("Sprite_2")
Sprite_2:setTag(7)
Sprite_2:setCascadeColorEnabled(true)
Sprite_2:setCascadeOpacityEnabled(true)
Sprite_2:setPosition(142.0000, 373.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_2)
layout:setPositionPercentX(0.2219)
layout:setPositionPercentY(0.3885)
layout:setPercentWidth(0.2578)
layout:setPercentHeight(0.0896)
layout:setSize({width = 165.0000, height = 86.0000})
layout:setLeftMargin(59.5000)
layout:setRightMargin(415.5000)
layout:setTopMargin(544.0000)
layout:setBottomMargin(330.0000)
Sprite_2:setBlendFunc({src = 1, dst = 771})
Layer:addChild(Sprite_2)

--Create Map_1
local Map_1 = cc.TMXTiledMap:create("Resource/stage1_1.tmx")
Map_1:setName("Map_1")
Map_1:setTag(52)
Map_1:setCascadeColorEnabled(true)
Map_1:setCascadeOpacityEnabled(true)
Map_1:setPosition(-58.0000, -54.8172)
layout = ccui.LayoutComponent:bindLayoutComponent(Map_1)
layout:setPositionPercentX(-0.0906)
layout:setPositionPercentY(-0.0571)
layout:setPercentWidth(1.2031)
layout:setPercentHeight(1.0250)
layout:setSize({width = 770.0000, height = 984.0000})
layout:setLeftMargin(-58.0000)
layout:setRightMargin(-72.0000)
layout:setTopMargin(30.8172)
layout:setBottomMargin(-54.8172)
Layer:addChild(Map_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(40)
result['animation']:setTimeSpeed(1.0000)

--Create FileDataTimeline
local FileDataTimeline = ccs.Timeline:create()

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/common.plist")
localFrame:setTextureName("btn-165-86-1.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(5)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/common.plist")
localFrame:setTextureName("btn-165-86-2.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/common.plist")
localFrame:setTextureName("btn-165-86-3.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(15)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/common.plist")
localFrame:setTextureName("btn-165-86-4.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(20)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/common.plist")
localFrame:setTextureName("btn-200-90-1.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(25)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/common.plist")
localFrame:setTextureName("btn-200-90-2.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/common.plist")
localFrame:setTextureName("btn-200-90-3.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/common.plist")
localFrame:setTextureName("btn-200-90-4.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(40)
localFrame:setTween(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/common.plist")
localFrame:setTextureName("btn-200-90-5.png")
FileDataTimeline:addFrame(localFrame)

result['animation']:addTimeline(FileDataTimeline)
FileDataTimeline:setNode(Sprite_2)
--Create Animation List
local animation0 = {name="animation0", startIndex=0, endIndex=40}
result['animation']:addAnimationInfo(animation0)

result['root'] = Layer
return result;
end

return Result

