--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_1:setBackGroundColorOpacity(0)
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(38)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setAnchorPoint(0.5000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setSize({width = 640.0000, height = 960.0000})
layout:setLeftMargin(-320.0000)
layout:setRightMargin(-320.0000)
layout:setTopMargin(-960.0000)
Node:addChild(Panel_1)

--Create bottom_1
local bottom_1 = cc.Sprite:create("Resource/atlas/bottom.png")
bottom_1:setName("bottom_1")
bottom_1:setTag(39)
bottom_1:setCascadeColorEnabled(true)
bottom_1:setCascadeOpacityEnabled(true)
bottom_1:setPosition(325.0321, 60.8264)
layout = ccui.LayoutComponent:bindLayoutComponent(bottom_1)
layout:setPositionPercentX(0.5079)
layout:setPositionPercentY(0.0634)
layout:setPercentWidth(1.1250)
layout:setPercentHeight(0.2260)
layout:setSize({width = 720.0000, height = 217.0000})
layout:setLeftMargin(-34.9679)
layout:setRightMargin(-45.0321)
layout:setTopMargin(790.6736)
layout:setBottomMargin(-47.6736)
bottom_1:setBlendFunc({src = 1, dst = 771})
Panel_1:addChild(bottom_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

