--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create Sprite_1
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/common.plist")
local Sprite_1 = cc.Sprite:createWithSpriteFrameName("star-star.png")
Sprite_1:setName("Sprite_1")
Sprite_1:setTag(27)
Sprite_1:setCascadeColorEnabled(true)
Sprite_1:setCascadeOpacityEnabled(true)
Sprite_1:setPosition(300.9347, 1021.0280)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_1)
layout:setPositionPercentX(0.4012)
layout:setPositionPercentY(0.7654)
layout:setPercentWidth(0.2320)
layout:setPercentHeight(0.1402)
layout:setSize({width = 174.0000, height = 187.0000})
layout:setLeftMargin(213.9347)
layout:setRightMargin(362.0653)
layout:setTopMargin(219.4717)
layout:setBottomMargin(927.5283)
Sprite_1:setBlendFunc({src = 1, dst = 771})
Scene:addChild(Sprite_1)

--Create Sprite_2
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/common.plist")
local Sprite_2 = cc.Sprite:createWithSpriteFrameName("star-star.png")
Sprite_2:setName("Sprite_2")
Sprite_2:setTag(28)
Sprite_2:setCascadeColorEnabled(true)
Sprite_2:setCascadeOpacityEnabled(true)
Sprite_2:setPosition(741.5901, 1332.7110)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_2)
layout:setPositionPercentX(0.9888)
layout:setPositionPercentY(0.9990)
layout:setPercentWidth(0.2320)
layout:setPercentHeight(0.1402)
layout:setSize({width = 174.0000, height = 187.0000})
layout:setLeftMargin(654.5901)
layout:setRightMargin(-78.5901)
layout:setTopMargin(-92.2112)
layout:setBottomMargin(1239.2110)
Sprite_2:setBlendFunc({src = 1, dst = 771})
Scene:addChild(Sprite_2)

--Create Sprite_3
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/common.plist")
local Sprite_3 = cc.Sprite:createWithSpriteFrameName("star-star.png")
Sprite_3:setName("Sprite_3")
Sprite_3:setTag(29)
Sprite_3:setCascadeColorEnabled(true)
Sprite_3:setCascadeOpacityEnabled(true)
Sprite_3:setPosition(-60.1869, 614.7665)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_3)
layout:setPositionPercentX(-0.0802)
layout:setPositionPercentY(0.4608)
layout:setPercentWidth(0.2320)
layout:setPercentHeight(0.1402)
layout:setSize({width = 174.0000, height = 187.0000})
layout:setLeftMargin(-147.1869)
layout:setRightMargin(723.1869)
layout:setTopMargin(625.7335)
layout:setBottomMargin(521.2665)
Sprite_3:setBlendFunc({src = 1, dst = 771})
Scene:addChild(Sprite_3)

--Create Sprite_4
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/common.plist")
local Sprite_4 = cc.Sprite:createWithSpriteFrameName("star-star.png")
Sprite_4:setName("Sprite_4")
Sprite_4:setTag(30)
Sprite_4:setCascadeColorEnabled(true)
Sprite_4:setCascadeOpacityEnabled(true)
Sprite_4:setPosition(4.3028, 10.7491)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_4)
layout:setPositionPercentX(0.0057)
layout:setPositionPercentY(0.0081)
layout:setPercentWidth(0.2320)
layout:setPercentHeight(0.1402)
layout:setSize({width = 174.0000, height = 187.0000})
layout:setLeftMargin(-82.6972)
layout:setRightMargin(658.6972)
layout:setTopMargin(1229.7510)
layout:setBottomMargin(-82.7509)
Sprite_4:setBlendFunc({src = 1, dst = 771})
Scene:addChild(Sprite_4)

--Create Sprite_5
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/common.plist")
local Sprite_5 = cc.Sprite:createWithSpriteFrameName("star-star.png")
Sprite_5:setName("Sprite_5")
Sprite_5:setTag(31)
Sprite_5:setCascadeColorEnabled(true)
Sprite_5:setCascadeOpacityEnabled(true)
Sprite_5:setPosition(713.6451, 659.9067)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_5)
layout:setPositionPercentX(0.9515)
layout:setPositionPercentY(0.4947)
layout:setPercentWidth(0.2320)
layout:setPercentHeight(0.1402)
layout:setSize({width = 174.0000, height = 187.0000})
layout:setLeftMargin(626.6451)
layout:setRightMargin(-50.6451)
layout:setTopMargin(580.5933)
layout:setBottomMargin(566.4067)
Sprite_5:setBlendFunc({src = 1, dst = 771})
Scene:addChild(Sprite_5)

--Create Sprite_6
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/common.plist")
local Sprite_6 = cc.Sprite:createWithSpriteFrameName("star-star.png")
Sprite_6:setName("Sprite_6")
Sprite_6:setTag(32)
Sprite_6:setCascadeColorEnabled(true)
Sprite_6:setCascadeOpacityEnabled(true)
Sprite_6:setPosition(739.4407, 2.1508)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_6)
layout:setPositionPercentX(0.9859)
layout:setPositionPercentY(0.0016)
layout:setPercentWidth(0.2320)
layout:setPercentHeight(0.1402)
layout:setSize({width = 174.0000, height = 187.0000})
layout:setLeftMargin(652.4407)
layout:setRightMargin(-76.4407)
layout:setTopMargin(1238.3490)
layout:setBottomMargin(-91.3492)
Sprite_6:setBlendFunc({src = 1, dst = 771})
Scene:addChild(Sprite_6)

--Create Sprite_7
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/common.plist")
local Sprite_7 = cc.Sprite:createWithSpriteFrameName("star-star.png")
Sprite_7:setName("Sprite_7")
Sprite_7:setTag(33)
Sprite_7:setCascadeColorEnabled(true)
Sprite_7:setCascadeOpacityEnabled(true)
Sprite_7:setPosition(8.5992, 1330.5620)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_7)
layout:setPositionPercentX(0.0115)
layout:setPositionPercentY(0.9974)
layout:setPercentWidth(0.2320)
layout:setPercentHeight(0.1402)
layout:setSize({width = 174.0000, height = 187.0000})
layout:setLeftMargin(-78.4008)
layout:setRightMargin(654.4008)
layout:setTopMargin(-90.0616)
layout:setBottomMargin(1237.0620)
Sprite_7:setBlendFunc({src = 1, dst = 771})
Scene:addChild(Sprite_7)

--Create Button_1
local Button_1 = ccui.Button:create()
Button_1:ignoreContentAdaptWithSize(false)
Button_1:loadTextureNormal("Default/Button_Normal.png",0)
Button_1:loadTexturePressed("Default/Button_Press.png",0)
Button_1:loadTextureDisabled("Default/Button_Disable.png",0)
Button_1:setTitleFontSize(14)
Button_1:setTitleText("Button")
Button_1:setTitleColor({r = 65, g = 65, b = 70})
Button_1:setScale9Enabled(true)
Button_1:setCapInsets({x = 15, y = 11, width = 16, height = 14})
Button_1:setLayoutComponentEnabled(true)
Button_1:setName("Button_1")
Button_1:setTag(46)
Button_1:setCascadeColorEnabled(true)
Button_1:setCascadeOpacityEnabled(true)
Button_1:setPosition(184.8599, 826.0089)
if callBackProvider~=nil then
      Button_1:addClickEventListener(callBackProvider("scene_main.lua", Button_1, "ontttt"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(Button_1)
layout:setPositionPercentX(0.2465)
layout:setPositionPercentY(0.6192)
layout:setPercentWidth(0.0613)
layout:setPercentHeight(0.0270)
layout:setSize({width = 46.0000, height = 36.0000})
layout:setLeftMargin(161.8599)
layout:setRightMargin(542.1401)
layout:setTopMargin(489.9911)
layout:setBottomMargin(808.0089)
Scene:addChild(Button_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

