--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Button_1
local Button_1 = ccui.Button:create()
Button_1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/common.plist")
Button_1:loadTextureNormal("btn-back.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/common.plist")
Button_1:loadTexturePressed("btn-back.png",1)
Button_1:loadTextureDisabled("Default/Button_Disable.png",0)
Button_1:setTitleFontSize(14)
Button_1:setTitleText("Button")
Button_1:setTitleColor({r = 65, g = 65, b = 70})
Button_1:setScale9Enabled(true)
Button_1:setCapInsets({x = 15, y = 11, width = 139, height = 119})
Button_1:setLayoutComponentEnabled(true)
Button_1:setName("Button_1")
Button_1:setTag(11)
Button_1:setCascadeColorEnabled(true)
Button_1:setCascadeOpacityEnabled(true)
Button_1:setPosition(278.1542, 100.1528)
if callBackProvider~=nil then
      Button_1:addClickEventListener(callBackProvider("shaderTest.lua", Button_1, "backClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(Button_1)
layout:setPositionPercentX(0.2576)
layout:setPositionPercentY(0.0522)
layout:setPercentWidth(0.1565)
layout:setPercentHeight(0.0734)
layout:setSize({width = 169.0000, height = 141.0000})
layout:setLeftMargin(193.6542)
layout:setRightMargin(717.3458)
layout:setTopMargin(1749.3470)
layout:setBottomMargin(29.6528)
Layer:addChild(Button_1)

--Create Button_1_0
local Button_1_0 = ccui.Button:create()
Button_1_0:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/common.plist")
Button_1_0:loadTextureNormal("btn-back.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/common.plist")
Button_1_0:loadTexturePressed("btn-back.png",1)
Button_1_0:loadTextureDisabled("Default/Button_Disable.png",0)
Button_1_0:setTitleFontSize(14)
Button_1_0:setTitleText("Button")
Button_1_0:setTitleColor({r = 65, g = 65, b = 70})
Button_1_0:setScale9Enabled(true)
Button_1_0:setCapInsets({x = 15, y = 11, width = 139, height = 119})
Button_1_0:setLayoutComponentEnabled(true)
Button_1_0:setName("Button_1_0")
Button_1_0:setTag(12)
Button_1_0:setCascadeColorEnabled(true)
Button_1_0:setCascadeOpacityEnabled(true)
Button_1_0:setPosition(772.9205, 97.2272)
Button_1_0:setRotationSkewX(180.0000)
Button_1_0:setRotationSkewY(180.0000)
if callBackProvider~=nil then
      Button_1_0:addClickEventListener(callBackProvider("shaderTest.lua", Button_1_0, "preClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(Button_1_0)
layout:setPositionPercentX(0.7157)
layout:setPositionPercentY(0.0506)
layout:setPercentWidth(0.1565)
layout:setPercentHeight(0.0734)
layout:setSize({width = 169.0000, height = 141.0000})
layout:setLeftMargin(688.4205)
layout:setRightMargin(222.5795)
layout:setTopMargin(1752.2730)
layout:setBottomMargin(26.7272)
Layer:addChild(Button_1_0)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

